---
- name: create vm
  hosts: localhost
  connection: local
  collections:
    - community.general
  tasks:
  - name: vm
    community.vmware.vmware_guest:
      hostname: vc7.bgl1.global.tslabs.hpecorp.net
      username: admautomate@vsphere.local
      password: Password!234
      validate_certs: false
      datacenter: BGL
      folder: HCENext
      name: ubuntu-ans-vl1
      state: poweredon
      guest_id: ubuntu64Guest
      cdrom:
      - controller_number: 0
        controller_type: ide
        unit_number: 0
        state: present
        iso_path: "[ezmeral_01] ISO/Ubuntu/ubuntu-22.04-live-server-amd64.iso"
        type: iso
      disk:
      - size_gb: 20
        type: thin
        datastore: DEV-STORAGE
      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual
      networks:
      - name: "Management Network"
        connected: yes
        start_connected: yes
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 600
      #ashok
